// GENERATED by scripts/generate-method-table.mjs from Google's Discovery documents.
// Do not edit by hand; re-run the script. The oracle test compares every entry
// src/tools uses against the pinned CLI's own reading of the same documents.

export interface MethodEntry {
  httpMethod: string;
  /** Discovery path template: {name} is a path segment, {+name} keeps slashes. */
  path: string;
  pathParams: string[];
  /** Query parameters the API reads as a repeated key. */
  repeated: string[];
  /** Query parameters Discovery marks required. */
  requiredQuery: string[];
  /** Whether the method takes a JSON request body. */
  hasBody?: boolean;
  mediaDownload?: boolean;
  mediaUpload?: { simple?: string; resumable?: string };
}

export interface ServiceEntry {
  rootUrl: string;
  servicePath: string;
  revision: string;
  methods: Record<string, MethodEntry>;
}

export const METHOD_TABLE: Record<string, ServiceEntry> = {
  "drive": {
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "drive/v3/",
    "revision": "20260913",
    "methods": {
      "about.get": {
        "httpMethod": "GET",
        "path": "about",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "accessproposals.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/accessproposals/{proposalId}",
        "pathParams": [
          "fileId",
          "proposalId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "accessproposals.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/accessproposals",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "accessproposals.resolve": {
        "httpMethod": "POST",
        "path": "files/{fileId}/accessproposals/{proposalId}:resolve",
        "pathParams": [
          "fileId",
          "proposalId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.approve": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals/{approvalId}:approve",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.cancel": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals/{approvalId}:cancel",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.comment": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals/{approvalId}:comment",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.decline": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals/{approvalId}:decline",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/approvals/{approvalId}",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "approvals.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/approvals",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "approvals.reassign": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals/{approvalId}:reassign",
        "pathParams": [
          "approvalId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "approvals.start": {
        "httpMethod": "POST",
        "path": "files/{fileId}/approvals:start",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "apps.get": {
        "httpMethod": "GET",
        "path": "apps/{appId}",
        "pathParams": [
          "appId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "apps.list": {
        "httpMethod": "GET",
        "path": "apps",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "changes.getStartPageToken": {
        "httpMethod": "GET",
        "path": "changes/startPageToken",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "changes.list": {
        "httpMethod": "GET",
        "path": "changes",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [
          "pageToken"
        ]
      },
      "changes.watch": {
        "httpMethod": "POST",
        "path": "changes/watch",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [
          "pageToken"
        ],
        "hasBody": true
      },
      "channels.stop": {
        "httpMethod": "POST",
        "path": "channels/stop",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "comments.create": {
        "httpMethod": "POST",
        "path": "files/{fileId}/comments",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "comments.delete": {
        "httpMethod": "DELETE",
        "path": "files/{fileId}/comments/{commentId}",
        "pathParams": [
          "commentId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "comments.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/comments/{commentId}",
        "pathParams": [
          "commentId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "comments.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/comments",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "comments.update": {
        "httpMethod": "PATCH",
        "path": "files/{fileId}/comments/{commentId}",
        "pathParams": [
          "commentId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "drives.create": {
        "httpMethod": "POST",
        "path": "drives",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [
          "requestId"
        ],
        "hasBody": true
      },
      "drives.delete": {
        "httpMethod": "DELETE",
        "path": "drives/{driveId}",
        "pathParams": [
          "driveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "drives.get": {
        "httpMethod": "GET",
        "path": "drives/{driveId}",
        "pathParams": [
          "driveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "drives.hide": {
        "httpMethod": "POST",
        "path": "drives/{driveId}/hide",
        "pathParams": [
          "driveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "drives.list": {
        "httpMethod": "GET",
        "path": "drives",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "drives.unhide": {
        "httpMethod": "POST",
        "path": "drives/{driveId}/unhide",
        "pathParams": [
          "driveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "drives.update": {
        "httpMethod": "PATCH",
        "path": "drives/{driveId}",
        "pathParams": [
          "driveId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "files.copy": {
        "httpMethod": "POST",
        "path": "files/{fileId}/copy",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "files.create": {
        "httpMethod": "POST",
        "path": "files",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/drive/v3/files",
          "resumable": "/resumable/upload/drive/v3/files"
        }
      },
      "files.delete": {
        "httpMethod": "DELETE",
        "path": "files/{fileId}",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "files.download": {
        "httpMethod": "POST",
        "path": "files/{fileId}/download",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "files.emptyTrash": {
        "httpMethod": "DELETE",
        "path": "files/trash",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "files.export": {
        "httpMethod": "GET",
        "path": "files/{fileId}/export",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [
          "mimeType"
        ],
        "mediaDownload": true
      },
      "files.generateCseToken": {
        "httpMethod": "GET",
        "path": "files/generateCseToken",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "files.generateIds": {
        "httpMethod": "GET",
        "path": "files/generateIds",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "files.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "mediaDownload": true
      },
      "files.list": {
        "httpMethod": "GET",
        "path": "files",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "files.listLabels": {
        "httpMethod": "GET",
        "path": "files/{fileId}/listLabels",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "files.modifyLabels": {
        "httpMethod": "POST",
        "path": "files/{fileId}/modifyLabels",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "files.update": {
        "httpMethod": "PATCH",
        "path": "files/{fileId}",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/drive/v3/files/{fileId}",
          "resumable": "/resumable/upload/drive/v3/files/{fileId}"
        }
      },
      "files.watch": {
        "httpMethod": "POST",
        "path": "files/{fileId}/watch",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "operations.get": {
        "httpMethod": "GET",
        "path": "operations/{name}",
        "pathParams": [
          "name"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "permissions.create": {
        "httpMethod": "POST",
        "path": "files/{fileId}/permissions",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "permissions.delete": {
        "httpMethod": "DELETE",
        "path": "files/{fileId}/permissions/{permissionId}",
        "pathParams": [
          "fileId",
          "permissionId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "permissions.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/permissions/{permissionId}",
        "pathParams": [
          "fileId",
          "permissionId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "permissions.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/permissions",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "permissions.update": {
        "httpMethod": "PATCH",
        "path": "files/{fileId}/permissions/{permissionId}",
        "pathParams": [
          "fileId",
          "permissionId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "replies.create": {
        "httpMethod": "POST",
        "path": "files/{fileId}/comments/{commentId}/replies",
        "pathParams": [
          "commentId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "replies.delete": {
        "httpMethod": "DELETE",
        "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
        "pathParams": [
          "commentId",
          "fileId",
          "replyId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "replies.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
        "pathParams": [
          "commentId",
          "fileId",
          "replyId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "replies.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/comments/{commentId}/replies",
        "pathParams": [
          "commentId",
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "replies.update": {
        "httpMethod": "PATCH",
        "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
        "pathParams": [
          "commentId",
          "fileId",
          "replyId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "revisions.delete": {
        "httpMethod": "DELETE",
        "path": "files/{fileId}/revisions/{revisionId}",
        "pathParams": [
          "fileId",
          "revisionId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "revisions.get": {
        "httpMethod": "GET",
        "path": "files/{fileId}/revisions/{revisionId}",
        "pathParams": [
          "fileId",
          "revisionId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "mediaDownload": true
      },
      "revisions.list": {
        "httpMethod": "GET",
        "path": "files/{fileId}/revisions",
        "pathParams": [
          "fileId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "revisions.update": {
        "httpMethod": "PATCH",
        "path": "files/{fileId}/revisions/{revisionId}",
        "pathParams": [
          "fileId",
          "revisionId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "teamdrives.create": {
        "httpMethod": "POST",
        "path": "teamdrives",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [
          "requestId"
        ],
        "hasBody": true
      },
      "teamdrives.delete": {
        "httpMethod": "DELETE",
        "path": "teamdrives/{teamDriveId}",
        "pathParams": [
          "teamDriveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "teamdrives.get": {
        "httpMethod": "GET",
        "path": "teamdrives/{teamDriveId}",
        "pathParams": [
          "teamDriveId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "teamdrives.list": {
        "httpMethod": "GET",
        "path": "teamdrives",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "teamdrives.update": {
        "httpMethod": "PATCH",
        "path": "teamdrives/{teamDriveId}",
        "pathParams": [
          "teamDriveId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  },
  "gmail": {
    "rootUrl": "https://gmail.googleapis.com/",
    "servicePath": "",
    "revision": "20260907",
    "methods": {
      "users.drafts.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/drafts",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/drafts",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/drafts"
        }
      },
      "users.drafts.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/drafts/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.drafts.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/drafts/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.drafts.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/drafts",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.drafts.send": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/drafts/send",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/drafts/send",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/drafts/send"
        }
      },
      "users.drafts.update": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/drafts/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/drafts/{id}",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/drafts/{id}"
        }
      },
      "users.getProfile": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/profile",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.history.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/history",
        "pathParams": [
          "userId"
        ],
        "repeated": [
          "historyTypes"
        ],
        "requiredQuery": []
      },
      "users.labels.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/labels",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.labels.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/labels/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.labels.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/labels/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.labels.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/labels",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.labels.patch": {
        "httpMethod": "PATCH",
        "path": "gmail/v1/users/{userId}/labels/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.labels.update": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/labels/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.messages.attachments.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
        "pathParams": [
          "id",
          "messageId",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.messages.batchDelete": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/batchDelete",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.messages.batchModify": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/batchModify",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.messages.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/messages/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.messages.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/messages/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [
          "metadataHeaders"
        ],
        "requiredQuery": []
      },
      "users.messages.import": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/import",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/messages/import",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/messages/import"
        }
      },
      "users.messages.insert": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/messages",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/messages"
        }
      },
      "users.messages.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/messages",
        "pathParams": [
          "userId"
        ],
        "repeated": [
          "labelIds"
        ],
        "requiredQuery": []
      },
      "users.messages.modify": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/{id}/modify",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.messages.send": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/send",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true,
        "mediaUpload": {
          "simple": "/upload/gmail/v1/users/{userId}/messages/send",
          "resumable": "/resumable/upload/gmail/v1/users/{userId}/messages/send"
        }
      },
      "users.messages.trash": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/{id}/trash",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.messages.untrash": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.identities.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/cse/identities",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.cse.identities.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
        "pathParams": [
          "cseEmailAddress",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.identities.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
        "pathParams": [
          "cseEmailAddress",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.identities.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/cse/identities",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.identities.patch": {
        "httpMethod": "PATCH",
        "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
        "pathParams": [
          "emailAddress",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.cse.keypairs.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.cse.keypairs.disable": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
        "pathParams": [
          "keyPairId",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.cse.keypairs.enable": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
        "pathParams": [
          "keyPairId",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.cse.keypairs.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
        "pathParams": [
          "keyPairId",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.keypairs.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.cse.keypairs.obliterate": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
        "pathParams": [
          "keyPairId",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.delegates.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/delegates",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.delegates.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
        "pathParams": [
          "delegateEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.delegates.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
        "pathParams": [
          "delegateEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.delegates.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/delegates",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.filters.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/filters",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.filters.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/filters/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.filters.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/filters/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.filters.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/filters",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.forwardingAddresses.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.forwardingAddresses.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
        "pathParams": [
          "forwardingEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.forwardingAddresses.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
        "pathParams": [
          "forwardingEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.forwardingAddresses.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.getAutoForwarding": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/autoForwarding",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.getImap": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/imap",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.getLanguage": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/language",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.getPop": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/pop",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.getVacation": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/vacation",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.create": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/sendAs",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.sendAs.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/sendAs",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.patch": {
        "httpMethod": "PATCH",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.sendAs.smimeInfo.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
        "pathParams": [
          "id",
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.smimeInfo.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
        "pathParams": [
          "id",
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.smimeInfo.insert": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.sendAs.smimeInfo.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.smimeInfo.setDefault": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
        "pathParams": [
          "id",
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.sendAs.update": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.sendAs.verify": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
        "pathParams": [
          "sendAsEmail",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.settings.updateAutoForwarding": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/autoForwarding",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.updateImap": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/imap",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.updateLanguage": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/language",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.updatePop": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/pop",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.settings.updateVacation": {
        "httpMethod": "PUT",
        "path": "gmail/v1/users/{userId}/settings/vacation",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.stop": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/stop",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.threads.delete": {
        "httpMethod": "DELETE",
        "path": "gmail/v1/users/{userId}/threads/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.threads.get": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/threads/{id}",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [
          "metadataHeaders"
        ],
        "requiredQuery": []
      },
      "users.threads.list": {
        "httpMethod": "GET",
        "path": "gmail/v1/users/{userId}/threads",
        "pathParams": [
          "userId"
        ],
        "repeated": [
          "labelIds"
        ],
        "requiredQuery": []
      },
      "users.threads.modify": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/threads/{id}/modify",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "users.threads.trash": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/threads/{id}/trash",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.threads.untrash": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
        "pathParams": [
          "id",
          "userId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "users.watch": {
        "httpMethod": "POST",
        "path": "gmail/v1/users/{userId}/watch",
        "pathParams": [
          "userId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  },
  "sheets": {
    "rootUrl": "https://sheets.googleapis.com/",
    "servicePath": "",
    "revision": "20260909",
    "methods": {
      "spreadsheets.batchUpdate": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.create": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.developerMetadata.get": {
        "httpMethod": "GET",
        "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
        "pathParams": [
          "metadataId",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "spreadsheets.developerMetadata.search": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.get": {
        "httpMethod": "GET",
        "path": "v4/spreadsheets/{spreadsheetId}",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [
          "ranges"
        ],
        "requiredQuery": []
      },
      "spreadsheets.getByDataFilter": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.sheets.copyTo": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
        "pathParams": [
          "sheetId",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.append": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
        "pathParams": [
          "range",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.batchClear": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.batchClearByDataFilter": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.batchGet": {
        "httpMethod": "GET",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [
          "ranges"
        ],
        "requiredQuery": []
      },
      "spreadsheets.values.batchGetByDataFilter": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.batchUpdate": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.batchUpdateByDataFilter": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
        "pathParams": [
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.clear": {
        "httpMethod": "POST",
        "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
        "pathParams": [
          "range",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "spreadsheets.values.get": {
        "httpMethod": "GET",
        "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
        "pathParams": [
          "range",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "spreadsheets.values.update": {
        "httpMethod": "PUT",
        "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
        "pathParams": [
          "range",
          "spreadsheetId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  },
  "calendar": {
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "calendar/v3/",
    "revision": "20260826",
    "methods": {
      "acl.delete": {
        "httpMethod": "DELETE",
        "path": "calendars/{calendarId}/acl/{ruleId}",
        "pathParams": [
          "calendarId",
          "ruleId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "acl.get": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}/acl/{ruleId}",
        "pathParams": [
          "calendarId",
          "ruleId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "acl.insert": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/acl",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "acl.list": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}/acl",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "acl.patch": {
        "httpMethod": "PATCH",
        "path": "calendars/{calendarId}/acl/{ruleId}",
        "pathParams": [
          "calendarId",
          "ruleId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "acl.update": {
        "httpMethod": "PUT",
        "path": "calendars/{calendarId}/acl/{ruleId}",
        "pathParams": [
          "calendarId",
          "ruleId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "acl.watch": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/acl/watch",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendarList.delete": {
        "httpMethod": "DELETE",
        "path": "users/me/calendarList/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "calendarList.get": {
        "httpMethod": "GET",
        "path": "users/me/calendarList/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "calendarList.insert": {
        "httpMethod": "POST",
        "path": "users/me/calendarList",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendarList.list": {
        "httpMethod": "GET",
        "path": "users/me/calendarList",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "calendarList.patch": {
        "httpMethod": "PATCH",
        "path": "users/me/calendarList/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendarList.update": {
        "httpMethod": "PUT",
        "path": "users/me/calendarList/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendarList.watch": {
        "httpMethod": "POST",
        "path": "users/me/calendarList/watch",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendars.clear": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/clear",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "calendars.delete": {
        "httpMethod": "DELETE",
        "path": "calendars/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "calendars.get": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "calendars.insert": {
        "httpMethod": "POST",
        "path": "calendars",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendars.patch": {
        "httpMethod": "PATCH",
        "path": "calendars/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "calendars.transferOwnership": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/transferOwnership",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [
          "newDataOwner",
          "useAdminAccess"
        ]
      },
      "calendars.update": {
        "httpMethod": "PUT",
        "path": "calendars/{calendarId}",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "channels.stop": {
        "httpMethod": "POST",
        "path": "channels/stop",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "colors.get": {
        "httpMethod": "GET",
        "path": "colors",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "events.delete": {
        "httpMethod": "DELETE",
        "path": "calendars/{calendarId}/events/{eventId}",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "events.get": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}/events/{eventId}",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "events.import": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/events/import",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "events.insert": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/events",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "events.instances": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}/events/{eventId}/instances",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "events.list": {
        "httpMethod": "GET",
        "path": "calendars/{calendarId}/events",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [
          "eventTypes",
          "privateExtendedProperty",
          "sharedExtendedProperty"
        ],
        "requiredQuery": []
      },
      "events.move": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/events/{eventId}/move",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": [
          "destination"
        ]
      },
      "events.patch": {
        "httpMethod": "PATCH",
        "path": "calendars/{calendarId}/events/{eventId}",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "events.quickAdd": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/events/quickAdd",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [],
        "requiredQuery": [
          "text"
        ]
      },
      "events.update": {
        "httpMethod": "PUT",
        "path": "calendars/{calendarId}/events/{eventId}",
        "pathParams": [
          "calendarId",
          "eventId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "events.watch": {
        "httpMethod": "POST",
        "path": "calendars/{calendarId}/events/watch",
        "pathParams": [
          "calendarId"
        ],
        "repeated": [
          "eventTypes",
          "privateExtendedProperty",
          "sharedExtendedProperty"
        ],
        "requiredQuery": [],
        "hasBody": true
      },
      "freebusy.query": {
        "httpMethod": "POST",
        "path": "freeBusy",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "settings.get": {
        "httpMethod": "GET",
        "path": "users/me/settings/{setting}",
        "pathParams": [
          "setting"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "settings.list": {
        "httpMethod": "GET",
        "path": "users/me/settings",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "settings.watch": {
        "httpMethod": "POST",
        "path": "users/me/settings/watch",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  },
  "docs": {
    "rootUrl": "https://docs.googleapis.com/",
    "servicePath": "",
    "revision": "20260909",
    "methods": {
      "documents.batchUpdate": {
        "httpMethod": "POST",
        "path": "v1/documents/{documentId}:batchUpdate",
        "pathParams": [
          "documentId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "documents.create": {
        "httpMethod": "POST",
        "path": "v1/documents",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "documents.get": {
        "httpMethod": "GET",
        "path": "v1/documents/{documentId}",
        "pathParams": [
          "documentId"
        ],
        "repeated": [],
        "requiredQuery": []
      }
    }
  },
  "slides": {
    "rootUrl": "https://slides.googleapis.com/",
    "servicePath": "",
    "revision": "20260914",
    "methods": {
      "presentations.batchUpdate": {
        "httpMethod": "POST",
        "path": "v1/presentations/{presentationId}:batchUpdate",
        "pathParams": [
          "presentationId"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "presentations.create": {
        "httpMethod": "POST",
        "path": "v1/presentations",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "presentations.get": {
        "httpMethod": "GET",
        "path": "v1/presentations/{+presentationId}",
        "pathParams": [
          "presentationId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "presentations.pages.get": {
        "httpMethod": "GET",
        "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
        "pathParams": [
          "pageObjectId",
          "presentationId"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "presentations.pages.getThumbnail": {
        "httpMethod": "GET",
        "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
        "pathParams": [
          "pageObjectId",
          "presentationId"
        ],
        "repeated": [],
        "requiredQuery": []
      }
    }
  },
  "people": {
    "rootUrl": "https://people.googleapis.com/",
    "servicePath": "",
    "revision": "20260916",
    "methods": {
      "contactGroups.batchGet": {
        "httpMethod": "GET",
        "path": "v1/contactGroups:batchGet",
        "pathParams": [],
        "repeated": [
          "resourceNames"
        ],
        "requiredQuery": []
      },
      "contactGroups.create": {
        "httpMethod": "POST",
        "path": "v1/contactGroups",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "contactGroups.delete": {
        "httpMethod": "DELETE",
        "path": "v1/{+resourceName}",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "contactGroups.get": {
        "httpMethod": "GET",
        "path": "v1/{+resourceName}",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "contactGroups.list": {
        "httpMethod": "GET",
        "path": "v1/contactGroups",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "contactGroups.members.modify": {
        "httpMethod": "POST",
        "path": "v1/{+resourceName}/members:modify",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "contactGroups.update": {
        "httpMethod": "PUT",
        "path": "v1/{+resourceName}",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "otherContacts.copyOtherContactToMyContactsGroup": {
        "httpMethod": "POST",
        "path": "v1/{+resourceName}:copyOtherContactToMyContactsGroup",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "otherContacts.list": {
        "httpMethod": "GET",
        "path": "v1/otherContacts",
        "pathParams": [],
        "repeated": [
          "sources"
        ],
        "requiredQuery": []
      },
      "otherContacts.search": {
        "httpMethod": "GET",
        "path": "v1/otherContacts:search",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "people.batchCreateContacts": {
        "httpMethod": "POST",
        "path": "v1/people:batchCreateContacts",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "people.batchDeleteContacts": {
        "httpMethod": "POST",
        "path": "v1/people:batchDeleteContacts",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "people.batchUpdateContacts": {
        "httpMethod": "POST",
        "path": "v1/people:batchUpdateContacts",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "people.connections.list": {
        "httpMethod": "GET",
        "path": "v1/{+resourceName}/connections",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [
          "sources"
        ],
        "requiredQuery": []
      },
      "people.createContact": {
        "httpMethod": "POST",
        "path": "v1/people:createContact",
        "pathParams": [],
        "repeated": [
          "sources"
        ],
        "requiredQuery": [],
        "hasBody": true
      },
      "people.deleteContact": {
        "httpMethod": "DELETE",
        "path": "v1/{+resourceName}:deleteContact",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "people.deleteContactPhoto": {
        "httpMethod": "DELETE",
        "path": "v1/{+resourceName}:deleteContactPhoto",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [
          "sources"
        ],
        "requiredQuery": []
      },
      "people.get": {
        "httpMethod": "GET",
        "path": "v1/{+resourceName}",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [
          "sources"
        ],
        "requiredQuery": []
      },
      "people.getBatchGet": {
        "httpMethod": "GET",
        "path": "v1/people:batchGet",
        "pathParams": [],
        "repeated": [
          "resourceNames",
          "sources"
        ],
        "requiredQuery": []
      },
      "people.listDirectoryPeople": {
        "httpMethod": "GET",
        "path": "v1/people:listDirectoryPeople",
        "pathParams": [],
        "repeated": [
          "mergeSources",
          "sources"
        ],
        "requiredQuery": []
      },
      "people.searchContacts": {
        "httpMethod": "GET",
        "path": "v1/people:searchContacts",
        "pathParams": [],
        "repeated": [
          "sources"
        ],
        "requiredQuery": []
      },
      "people.searchDirectoryPeople": {
        "httpMethod": "GET",
        "path": "v1/people:searchDirectoryPeople",
        "pathParams": [],
        "repeated": [
          "mergeSources",
          "sources"
        ],
        "requiredQuery": []
      },
      "people.updateContact": {
        "httpMethod": "PATCH",
        "path": "v1/{+resourceName}:updateContact",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [
          "sources"
        ],
        "requiredQuery": [],
        "hasBody": true
      },
      "people.updateContactPhoto": {
        "httpMethod": "PATCH",
        "path": "v1/{+resourceName}:updateContactPhoto",
        "pathParams": [
          "resourceName"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  },
  "tasks": {
    "rootUrl": "https://tasks.googleapis.com/",
    "servicePath": "",
    "revision": "20260915",
    "methods": {
      "tasklists.delete": {
        "httpMethod": "DELETE",
        "path": "tasks/v1/users/@me/lists/{tasklist}",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasklists.get": {
        "httpMethod": "GET",
        "path": "tasks/v1/users/@me/lists/{tasklist}",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasklists.insert": {
        "httpMethod": "POST",
        "path": "tasks/v1/users/@me/lists",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "tasklists.list": {
        "httpMethod": "GET",
        "path": "tasks/v1/users/@me/lists",
        "pathParams": [],
        "repeated": [],
        "requiredQuery": []
      },
      "tasklists.patch": {
        "httpMethod": "PATCH",
        "path": "tasks/v1/users/@me/lists/{tasklist}",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "tasklists.update": {
        "httpMethod": "PUT",
        "path": "tasks/v1/users/@me/lists/{tasklist}",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "tasks.clear": {
        "httpMethod": "POST",
        "path": "tasks/v1/lists/{tasklist}/clear",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasks.delete": {
        "httpMethod": "DELETE",
        "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
        "pathParams": [
          "task",
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasks.get": {
        "httpMethod": "GET",
        "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
        "pathParams": [
          "task",
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasks.insert": {
        "httpMethod": "POST",
        "path": "tasks/v1/lists/{tasklist}/tasks",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "tasks.list": {
        "httpMethod": "GET",
        "path": "tasks/v1/lists/{tasklist}/tasks",
        "pathParams": [
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasks.move": {
        "httpMethod": "POST",
        "path": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
        "pathParams": [
          "task",
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": []
      },
      "tasks.patch": {
        "httpMethod": "PATCH",
        "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
        "pathParams": [
          "task",
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      },
      "tasks.update": {
        "httpMethod": "PUT",
        "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
        "pathParams": [
          "task",
          "tasklist"
        ],
        "repeated": [],
        "requiredQuery": [],
        "hasBody": true
      }
    }
  }
};
