-- Journal backfill for databases whose schema was applied outside drizzle's
-- migrator (drizzle-kit push era): tells migrate() that 0000-0011 are already
-- applied, so the next `db:migrate` applies exactly the migrations that came
-- after, and the normal migration path works from then on.
--
-- PRECONDITION, NOT OPTIONAL: before running this, diff the target's schema
-- against a database built purely by migrate() from empty (columns, indexes,
-- constraints). This file asserts 0000-0011's effects are present; writing it
-- over a drifted schema makes the journal a lie, which is worse than no
-- journal. The 2026-08-14 dev-branch diff that authorized this file found the
-- journaled tables byte-identical. Two tables are deliberately NOT covered by
-- any journaled migration and are unaffected by this file: `leads`
-- (hand-written 0004_leads.sql, outside the journal) and `api_keys` (present
-- in the drizzle snapshots but created by no migration file).
--
-- Hashes are sha256 of each migration file's content, generated by running
-- migrate() against an empty database — never hand-computed (a wrong hash
-- makes that migration re-run). created_at values are the journal's
-- folderMillis, which is what the migrator compares to decide what is pending.
--
-- Idempotent: safe to re-run; existing rows are left alone. The guard matches
-- on created_at because that is the migrator's own notion of identity.

INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
SELECT v.hash, v.created_at
FROM (VALUES
  ('383bb332f881a63c3da653e683714253e96984113ab7d9bff87abd2199c6e22e', 1776712446353), -- 0000_woozy_pyro
  ('8ac7008df95d02f92aa282b2956d8f2118e2ca7a9af7365d23af05937f5181ba', 1776719260486), -- 0001_icy_venus
  ('7d2e0a5fbd16f15b448c74c413bf78dcd9bc38c7f5d13495ba8149efcc336f7a', 1779076983943), -- 0002_chief_xorn
  ('7c4bec05bf14ce6449f29870e8c9b95ce95009b286ee81912bdc9e970e813877', 1779836104250), -- 0003_paid_tiers
  ('4c7003bcb1078695f75137f796fc2f897044eb46a049936d89c1ab4dff8bc3d1', 1784271373103), -- 0004_smiling_hercules
  ('5bf8bd258a17efa6ddf267dbfc3e60693e3b5ae28ebf8ec5b46c5348b021194a', 1784355972614), -- 0005_faulty_legion
  ('597ab5f6ec717599037b61edf72f8cd684a87f4e0815203dff01bd2dd1614ee0', 1784520274365), -- 0006_mysterious_night_nurse
  ('0058a87705bb4e4d266fbee4275e5df5bfd4cf8f5b5672ac6a960f458033545e', 1784533777275), -- 0007_melted_hawkeye
  ('698b3e39a9063114905e7c5658c96ca8fcf63cfa2147d26c57e311d3465fee55', 1784580396198), -- 0008_fancy_the_initiative
  ('7189701844c44f1833990d3190121a131fe8b91cfae1fe2fbced48e7f1c6c78a', 1786126876820), -- 0009_naive_mentor
  ('075705635331d85fd9d6ef5fff038fbc3d00dd98ad049b264db00d3086218d16', 1786244906789), -- 0010_silent_miek
  ('8e9c8531d4e5f411c38fbcff497cace5ecf4551607dd156920b337fb134ed5cd', 1786348931175)  -- 0011_thankful_rhodey
) AS v(hash, created_at)
WHERE NOT EXISTS (
  SELECT 1 FROM drizzle.__drizzle_migrations m WHERE m.created_at = v.created_at
);

-- THE PRODUCTION RUN HAPPENS FROM INSIDE THE CONTAINER. Not from a laptop:
-- pulling the production DATABASE_URL onto a workstation is how a credential
-- leaked into a session transcript once already and had to be rotated. The
-- container already holds DATABASE_URL in its environment, and while
-- drizzle-kit is pruned from the prod image, drizzle-orm's runtime migrator
-- (drizzle-orm/<driver>/migrator) is present and is the supported path.
--
-- After running this file there: migrate() should apply exactly the
-- migrations after 0011. Run it twice — the second run must be a no-op, and
-- proving the no-op means reading the journal row count, not trusting the
-- success message (it prints either way).
